Code Review
2010-CPU/code-warriors pull request #108
Opened 2021-04-08 02:28 UTC by crystaljoyce

2021-04-08 03:10 UTC, deannawong requested changes

2021-04-08 03:10 UTC, deannawong commented on db/reviews.js
> +const updateReview = async ({id, title, content, stars, userId, productId}) => {
Required - update this database method with fields object instead.

2021-04-08 03:10 UTC, deannawong commented on db/users.js
> +const createUser = async ({firstName, lastName, email, username, password, isAdmin=false, address, city, state, zip}) => {
Please make note to update User's database table if default false isn't working.

2021-04-08 03:10 UTC, deannawong commented on public/index.html
> +<footer>
There's no content in this footer. Stash it for when there is!

2021-04-08 03:10 UTC, deannawong commented on routes/index.js
> +apiRouter.post('/create-checkout-session', async (req, res, next) => {
Please make sure to remove test data when Cart is working.

2021-04-08 03:10 UTC, deannawong commented on routes/reviews.js
> +reviewsRouter.post('/', requireUser, async (req, res, next) => {
Required -  Missing destructuring of contents from req.body.

2021-04-08 03:10 UTC, deannawong commented on routes/reviews.js
> +        const reviewToModify = await getReviewById({id})
Required - Make sure the the review is being edited by it's owner.

2021-04-08 03:10 UTC, deannawong commented on routes/reviews.js
> +reviewsRouter.delete('/:reviewId', requireUser, async (req, res, next) => {
Required - Reviews should only be deleted by it's owner. 
Hint - Create middleware for "requireOwner"

2021-04-08 03:10 UTC, deannawong commented on src/components/AccountForm.js
> +                            <input type='text' value={email} required onChange={event => setEmail(event.target.value)} ></input>
Revert  type for input back to email.

2021-04-08 03:10 UTC, deannawong commented on src/components/Cart.js
> +    const fetchCart = async () =>{
Required -  Keep either fetchCart functions, not both.

2021-04-08 03:24 UTC, crystaljoyce commented on db/users.js
> +const createUser = async ({firstName, lastName, email, username, password, isAdmin=false, address, city, state, zip}) => {
This has been updated. Thank you!

2021-04-08 03:30 UTC, crystaljoyce commented on public/index.html
> +<footer>
This has been updated. Thank you!

2021-04-08 03:30 UTC, crystaljoyce commented on routes/reviews.js
> +reviewsRouter.post('/', requireUser, async (req, res, next) => {
This has been updated, thank you!

2021-04-08 03:31 UTC, crystaljoyce commented on routes/reviews.js
> +        const reviewToModify = await getReviewById({id})
Yeah, I am planning on doing this on the front end. Edit button will not appear unless the review owner is viewing their own review.

2021-04-08 03:31 UTC, crystaljoyce commented on routes/reviews.js
> +reviewsRouter.delete('/:reviewId', requireUser, async (req, res, next) => {
Yeah, I am planning on doing this on the front end. Delete button will not appear unless the review owner is viewing their own review.

2021-04-09 00:40 UTC, crystaljoyce commented on db/reviews.js
> +const updateReview = async ({id, title, content, stars, userId, productId}) => {
This has been updated. Thanks!

2021-04-15 04:10 UTC, deannawong approved these changes
Approved for merging into main (as back-up).
- Missing bug fixes for going to Cart route for exisiting user. 
- Cartpersistence.js file needs to be removed if no longer in use.

2021-04-15 04:10 UTC, merged